### ISSUE TITLE
 Implement product detail page

### ISSUE THREAD

**Issue by brolag** [Vagabonds-Labs/cofiblocks#10]
Create a detailed view for each product, showing complete information such as description, price, and reviews.

- **Steps**:
  1. Build a product detail page template.
  2. Fetch product-specific data from the backend.
  3. Implement add-to-cart functionality.

- **Acceptance Criteria**: Users can view detailed product information and add the product to their cart from the product detail page.

Add to Cart blocked by: https://github.com/Vagabonds-Labs/cofiblocks/issues/6

**Comment by muguika** [comment]
Information needed in the product detail page when the product is available (there are still NFTs available)

![Product details](https://github.com/user-attachments/assets/290ff0e7-20d1-4bd3-bead-7bbdbcb67b27)

If the product is sold out (no NFTs available) 

![Product details (1)](https://github.com/user-attachments/assets/5faa26ad-9e52-4bd3-b7b4-84f8ae61be60)

**Comment by devcollinss** [comment]
Hello @brolag,

I am Collins Ikechukwu, and I am eager to take on this task. With 4 years of experience as a full-stack JavaScript developer, I have a strong background in developing frontend web applications, particularly using Next.js. I’ve  contributed to OnlyDust in projects involving Next.js, Cairo, TypeScript, and JavaScript. I’m confident that I can handle this task effectively and would be grateful if you could assign it to me.

**Comment by Benjtalkshow** [comment]
Hello @brolag,

I am Nnaji Benjamin, and I am eager to take on this task. With 4 years of experience as a full-stack JavaScript developer, I have a strong background in building detailed product pages and integrating complex features using Next.js. I’ve contributed to over 18 projects on OnlyDust involving Next.js, TypeScript, and JavaScript, including tasks like developing detailed transaction pages and interactive dashboards. I’m confident in my ability to handle this task effectively and would be grateful if you could assign it to me.

Technical Approach:

1. Build a Product Detail Page Template: I will design and implement a comprehensive product detail page that displays complete information, including product descriptions, pricing, and user reviews. The design will be user-friendly and visually engaging.

2. Fetch Product-Specific Data: I will integrate API calls to fetch detailed data for each product from the backend, ensuring accurate and up-to-date information is displayed.

3. Implement Add-to-Cart Functionality: I will add functionality to allow users to easily add the product to their cart from the detail page, including updating the cart state and providing feedback to the user.

**Comment by muguika** [comment]
The Product Details Page has been updated to include additional info about the product and the farm, including a modal for extra information

you can access it directly here [Product Details Page](https://www.figma.com/design/E1g5hbzFkp0EAcBIc1SxSG/Delivery-(UI)?node-id=298-3140&t=xUnrJcjj6vqO2CnI-1)

**Comment by brolag** [comment]
Closing this since it is duplicated https://github.com/Vagabonds-Labs/cofiblocks/issues/32
