### ISSUE TITLE
Implement coffee collection creation

### ISSUE THREAD

**Issue by brolag** [Vagabonds-Labs/cofiblocks#15]
Allow coffee producers to create and manage collections of coffee products.

- **Steps**:
  1. Build a UI for creating new collections.
  2. Implement the smart contract interaction for miting new coffee product NFTs

- **Acceptance Criteria**: Coffee producers can create, edit, and manage coffee collections on the platform.

**Comment by devcollinss** [comment]
Hello @brolag,

I am Collins Ikechukwu, and I am eager to take on this task. With 4 years of experience as a full-stack JavaScript developer, I have a strong background in developing frontend web applications, particularly using Next.js. I’ve  contributed to OnlyDust in projects involving Next.js, Cairo, TypeScript, and JavaScript. I’m confident that I can handle this task effectively and would be grateful if you could assign it to me.

**Comment by Benjtalkshow** [comment]
Hello @brolag,

I am Nnaji Benjamin, and I am eager to take on this task. With 4 years of experience as a full-stack JavaScript developer, I have a robust background in building user interfaces and integrating blockchain functionalities using Next.js. I’ve contributed to over 18 projects on OnlyDust involving Next.js, TypeScript, and JavaScript, including tasks like implementing smart contract interactions and developing management interfaces. I’m confident in my ability to handle this task effectively and would be grateful if you could assign it to me.

Technical Approach:

1. Build a UI for Creating New Collections: I will design and implement a user-friendly interface that allows coffee producers to create and manage collections of coffee products. This will include forms for inputting collection details, managing product listings, and editing existing collections.

2. Implement Smart Contract Interaction: I will integrate functionality for interacting with smart contracts to mint new coffee product NFTs. This will involve creating and managing collections through the smart contract, ensuring producers can seamlessly add and update products in their collections.

**Comment by brolag** [comment]
Creation will be managed through the marketplace https://github.com/Vagabonds-Labs/cofiblocks/issues/17
