### ISSUE TITLE
Fix Storybook Configuration and Create Stories for Basic Components in @repo/ui

### ISSUE THREAD

**Issue by brolag** [Vagabonds-Labs/cofiblocks#20]
**Description**:
- Fix the existing Storybook configuration to ensure compatibility with TailwindCSS and TypeScript.
- Verify and update `.storybook/main.js` and `.storybook/preview.js` to properly support TailwindCSS, `@storybook/addon-essentials`, `@storybook/addon-interactions`, and `@storybook/addon-styling-webpack`.
- Ensure Storybook runs smoothly in the project with `npm run dev:storybook`.
- Create basic stories for the components in `@repo/ui`:
- Ensure each story showcases different variants (sizes, colors, states) for each component.
- Test all stories and ensure they're visually correct and function as expected.

**Acceptance Criteria**:
- Storybook should launch without errors.
- All basic components should have well-structured stories.
- TailwindCSS should work correctly inside Storybook.
- Verify proper display and behavior of components in various states.

**Comment by 0xdevcollins** [comment]
Hello @brolag  I can handle this issue. Can I be assigned the. Issue? Will deliver ASAP

**Comment by 0xdevcollins** [comment]
Hello @brolag can I work on this issue on this odhack?

I am a Full Stack Blockchain Developer with expertise in Next.js, TypeScript, React, Node.js, and Solidity/Rust. With 46 contributions across 10 OnlyDust projects, I bring technical excellence, adaptability, and a focus on user-centric blockchain solutions.

**Comment by josephchimebuka** [comment]
I’m interested in this one.

**Comment by josephchimebuka** [comment]
I’d love to work on this task.

**Comment by josephchimebuka** [comment]
Hello I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is a couple of frontend and blockchain projects i have built https://metacrypt.vercel.app/ https://mattedsgn.com/
May I pick this up?

**Comment by zintarh** [comment]
I'd love to give this a go.

**Comment by Benjtalkshow** [comment]
I'd like to handle this task.
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

MY ETA is 48hrs. Thanks

**Comment by ShantelPeters** [comment]
Is it okay if I take this?

**Comment by Michaelkingsdev** [comment]
May I handle this issue? I am an experienced frontend developer with 3 years of experience.

**Comment by martinvibes** [comment]
Can I take care of this issue?
i'm a frontend dev and a blockchain dev please kindly assign :)

**Comment by vestor-dev** [comment]
hey sir I'd like to handle this task.
i'm a frontend developer with experience
i would really love to contribute to your project 
kindly assign :)

**Comment by Kaminar-i** [comment]
Mind if I take this issue?
i'm new and would love to work on this

**Comment by JosueBrenes** [comment]
Hi, I'm Josué Brenes and I'll be working on issue.
I'm Dojo Coding member. ⛩️

I estimate this will take 3 day to complete.

## How I Would Resolve This

### Steps I Would Take:

1. **Fixing Storybook Configuration**  
   I would start by reviewing and updating the configuration files `storybook/main.js` and `storybook/preview.js`:
   - Ensure compatibility with TailwindCSS and TypeScript.
   - Add or verify the inclusion of the following addons:
     - `@storybook/addon-essentials`
     - `@storybook/addon-interactions`
     - `@storybook/addon-styling-webpack`.

2. **Testing Storybook**  
   I would run `npm run dev:storybook` to confirm that Storybook starts without any errors.

3. **Creating Component Stories**  
   I would create stories for the components located in `@repo/ui`. Each story would showcase:
   - Variants such as sizes, colors, and states for each component.
   - Comprehensive coverage to ensure every aspect of the components is demonstrated.

4. **Visual and Functional Validation**  
   I would thoroughly test all stories to ensure they:
   - Display correctly.
   - Behave as expected in various states.

### Acceptance Criteria I Would Verify:
- Storybook launches without errors.
- All basic components have well-structured stories.
- TailwindCSS works seamlessly inside Storybook.
- Components display and behave correctly across all variants and states.

---

**Comment by mimisavage** [comment]
Can I work on this, please?

**Comment by brolag** [comment]
Hi @zintarh you can start working on this.

**Comment by evgongora** [comment]
Hey @zintarh! Any updates on this? :)

**Comment by zintarh** [comment]
Gm @evgongora Yes, I'll create a PR today
