### ISSUE TITLE
Implement i18n

### ISSUE THREAD

**Issue by brolag** [Vagabonds-Labs/cofiblocks#4]
Add internationalization (i18n) support using `next-i18next` to enable multilingual support for the platform.

- **Steps**:
  1. Install and set up `next-i18next` library.
  2. Create language files for English and Spanish.
  3. Implement language switching in the UI.
 
- **Acceptance Criteria**: Users can switch between English and Spanish via a language toggle, with all platform content translated.
- **Resources**: [Next.js i18n Documentation](https://nextjs.org/docs/advanced-features/i18n-routing)

**Comment by muguika** [comment]
We are missing a language switching in the UI that is accesible. 
At the moment we only have it under Profile > Settings > Language   too many steps to get to it, will discuss this with the design team

**Comment by MaiCVCR** [comment]
Hi,

I'm a software developer with several years of experience, currently involved in web3 projects. I'm from Costa Rica and would love to contribute to this project.

Here's a brief overview of how I would approach this issue:

- **Set up next-i18next:** Install and configure it, creating language files for English and Spanish.

- **UI Language Switcher:** Move the language switcher to a more accessible location. I’m happy to await your input on the preferred placement of the language switcher within the UI.

- **Translate Content:** Implement full content translation and ensure smooth switching between languages.

- **Testing:** Test the functionality to ensure proper language switching and content translation.

**Comment by brolag** [comment]
@MaiCVCR assining this to you.

**Comment by MaiCVCR** [comment]
I just submitted a PR with the initial i18n configuration.

I also have a few questions regarding the setup you'd like:

- All translations are stored in JSON files. Do you prefer a single file for the entire application or one file per page (e.g., marketplace.json, home.json)?

![locales](https://github.com/user-attachments/assets/5272ccc6-715e-44e9-8024-e189f3ed6ff1)

- For storing the selected language, we have a few options: we can use cookies, localStorage, or include the language in the URL (e.g., /es/marketplace). Which option do you prefer?

**Comment by brolag** [comment]
@MaiCVCR 

Thanks for the follow up! 

Let's have a separate file for each page and regarding the laguage selection let's use a combination of localStorage (to remember the user option) and laguage in the url.

E.g. If the user chooses spanish, let's save "es" as prefered language and everytime the user logs into the app, they will be redirected to /es/url-route

Please let me know if it makes sense.
