### ISSUE TITLE
Implement Payment Claim for Producers

### ISSUE THREAD

**Issue by muguika** [Vagabonds-Labs/cofiblocks#42]
Once a sale is made and the product delivered, the producer must be able to claim their payment. Payment can be claimed after one or multiple sales. Notice it  bundles all receivables.

First version of UI is on [FIGMA](https://www.figma.com/design/E1g5hbzFkp0EAcBIc1SxSG/Delivery-(UI)?node-id=2-11) under PROFILE > My Claims

![Image](https://github.com/user-attachments/assets/61cf19b0-567a-4231-951b-128b8460987d)

**Comment by Jonatan-Chaverri** [comment]
Hello @muguika !
Can I help with this?

**Comment by brolag** [comment]
Assining this to you @Jonatan-Chaverri
