### ISSUE TITLE
Complete UI Translation

### ISSUE THREAD

**Issue by brolag** [Vagabonds-Labs/cofiblocks#55]
## Description
Ensure all missing strings in the UI are translated into **English**, **Spanish**, and **Portuguese** using the existing Next.js i18n setup.

## Steps
1. **Audit UI Strings**:
   - Identify all untranslated or hardcoded strings across the project.
   - Cross-check with the existing translation files (`public/locales/en`, `public/locales/es`, `public/locales/pt`).

2. **Add Missing Strings**:
   - Add missing keys to the respective JSON files for:
     - **English** (`en`)
     - **Spanish** (`es`)
     - **Portuguese** (`pt`)
   - Ensure key names are descriptive and follow the established naming conventions.

3. **Implement Translations**:
   - Replace hardcoded strings in the codebase with the `t` function from `next-i18next`.
   - Use placeholders and context handling for dynamic strings.

4. **Test Translations**:
   - Verify that translations are displayed correctly for **English**, **Spanish**, and **Portuguese**.
   - Use the language toggle feature (if available) to test switching between languages.

## Acceptance Criteria
- No untranslated strings remain in the UI.
- All translations are correctly reflected in **English**, **Spanish**, and **Portuguese**.
- Codebase is free from hardcoded UI strings.
- The website functions seamlessly when switching languages.

## Additional Notes
- The default language should remain **English**.
- Ensure translation keys are consistent and meaningful.
- Refer to [Next.js i18n Documentation](https://nextjs.org/docs/advanced-features/i18n-routing) for guidance.

---

**Comment by Jemiiah** [comment]
II would love to work on this issue @brolag this is my first time on this repository & I’m a frontend web3 developer

**Comment by Benjtalkshow** [comment]
Hello @brolag  I can take this task.

**Comment by PedroCo3lho** [comment]
Hello @brolag, can I work on this?

**Comment by wheval** [comment]
Hi @brolag , I'm a frontend developer. I can handle this task in one day.
Can i work on this? Thanks

**Comment by martinvibes** [comment]
Hey @brolag I would love to work on this issue

**Comment by josephchimebuka** [comment]
Hello I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is a couple of frontend and blockchain projects i have built https://metacrypt.vercel.app/ https://mattedsgn.com/
May I pick this up?

**Comment by CollinsC1O** [comment]
I would love to work on this and get it done

**Comment by abdegenius** [comment]
Can I contribute to this one? Would love to tackle this! I can comfortably handle this issues

**Comment by caxtonacollins** [comment]
Is it okay if I take this?

**Comment by Benjtalkshow** [comment]
I'd like to handle this task.
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

MY ETA is 48hrs. Thanks

**Comment by Michaelkingsdev** [comment]
May I handle this issue? I am an experienced frontend developer with 3 years of experience.

**Comment by LazarusAA** [comment]
Hi! I'm Alvaro Lazarus, a developer from Dojo Coding ⛩️. I haven’t worked with internationalization before, but I’m excited to learn and contribute to this issue! With my experience in front-end development and attention to detail, I’m confident I can help ensure the translations are implemented smoothly.

My workflow:

- Audit UI to find untranslated strings
- Add missing keys to en, es, and pt JSON files
- Replace hardcoded strings with the ```t``` function
- Test translations and language switching

ETA: 48 hrs

**Comment by Amarjeet325** [comment]
Can I try solving this issue?

**Comment by vestor-dev** [comment]
hey sir I'd like to handle this task.
i'm a frontend developer with experience
i would really love to contribute to your project 
kindly assign :)

**Comment by evgongora** [comment]
Hey @LazarusAA! Any updates so far? :)
