### ISSUE TITLE
Centralize Type Definitions

### ISSUE THREAD

**Issue by evgongora** [Vagabonds-Labs/cofiblocks#58]
Description:

Order-related types and enums are duplicated across files. We need to centralize these in a shared types file.

Code References:

### `my-orders`

```
const SalesStatusEnum = {
	Paid: "Paid",
	Prepared: "Prepared",
	Shipped: "Shipped",
	Delivered: "Delivered",
} as const;

type SalesStatus = (typeof SalesStatusEnum)[keyof typeof SalesStatusEnum];

const filtersSchema = z.object({
	statusPaid: z.boolean().optional(),
	statusPrepared: z.boolean().optional(),
	statusShipped: z.boolean().optional(),
	statusDelivered: z.boolean().optional(),
});

type FormValues = z.infer<typeof filtersSchema>;
```

### `my-sales`

```
const SalesStatusEnum = {
	Paid: "Paid",
	Prepared: "Prepared",
	Shipped: "Shipped",
	Delivered: "Delivered",
} as const;

type SalesStatus = (typeof SalesStatusEnum)[keyof typeof SalesStatusEnum];

const DeliveryMethodEnum = {
	Address: "Address",
	Meetup: "Meetup",
} as const;

type DeliveryMethod =
	(typeof DeliveryMethodEnum)[keyof typeof DeliveryMethodEnum];

const filtersSchema = z.object({
	statusPaid: z.boolean().optional(),
	statusPrepared: z.boolean().optional(),
	statusShipped: z.boolean().optional(),
	statusDelivered: z.boolean().optional(),
	deliveryAddress: z.boolean().optional(),
	deliveryMeetup: z.boolean().optional(),
});
```

Acceptance Criteria:

- Update all components to use shared types
- Ensure type safety across the application
- Create a shared file containing:

1. Status enums
2. Delivery method enums
3. Order interfaces
4. Form value types

**Comment by martinvibes** [comment]
Hey @evgongora can I work on this issue

**Comment by ShantelPeters** [comment]
Can i please be assigned to this issue @evgongora

**Comment by PedroCo3lho** [comment]
Hi @evgongora, can I work on this as my first issue in the project? I’m a full-stack developer with a solid understanding of TypeScript, Next.js, and TailwindCSS. 
I plan to organize all the types by creating a `\types` folder in `apps/web/src,` centralizing and modularizing the types based on their context. I will then export and update their usage throughout the `web` folder.
Looking forward to your approval!

**Comment by KevinLatino** [comment]
Hello @evgongora! My name is Kevin Latino, and I'm a frontend developer and active open-source contributor. I'm a member of Dojo Coding, a thriving Web3 community in Costa Rica. I have experience with React, Next.js, and TypeScript, also I have experience in data fetching and API integrations and I recently won the LATAM Hackathon hosted by Base.  I've also contributed to projects in ecosystems like Starknet and Stellar. 

For this issue, I will centralize the order-related types and enums in a shared types file to eliminate duplication. I will create a shared file that includes the status enums, delivery method enums, order interfaces, and form value types. I’ll update all components to use the shared types, ensuring type safety across the application.

**Comment by derianrddev** [comment]
My Background and How It Can Be Leveraged
Hello, my name is Derian Rodríguez. I am a passionate software engineer with over one year of experience. I am part of the Dojo Coding Community and have been actively contributing to open-source projects through OnlyDust. I have experience in frontend development using JavaScript/TypeScript, React, and Next.js. I would love to contribute and support the development of this project.

How I Plan on Tackling This Issue
I will create a shared file for types and enums.
I will modify the MyOrders and MySales pages to import enums and types from the new file.
I will verify that all components dependent on the updated types work correctly.

**Comment by PedroCo3lho** [comment]
> Hi @evgongora, can I work on this as my first issue in the project? I’m a full-stack developer with a solid understanding of TypeScript, Next.js, and TailwindCSS. I plan to organize all the types by creating a `\types` folder in `apps/web/src,` centralizing and modularizing the types based on their context. I will then export and update their usage throughout the `web` folder. Looking forward to your approval!

Can I try solving this issue?

**Comment by caxtonacollins** [comment]
please assign this issue to me, I am ready to put in the work

**Comment by hannahredler** [comment]
Hey! I'm Hannah, a full stack dev with several years experience in web3! I have a strong focus on clean code and would happily take this task, centralizing type definitions, reducing duplication and making sure it still works correctly.

**Comment by GideonBature** [comment]
Would love to tackle this!

My name is Gideon Bature, a Software Engineer with experience using TypeScript. If assigned this issue, I will send my first PR within 72 hrs. 

Thank you!

**Comment by Michaelkingsdev** [comment]
May I handle this issue? I am an experienced frontend developer with 3 years of experience.

**Comment by brolag** [comment]
@KevinLatino assigning this to you.

**Comment by PedroCo3lho** [comment]
Thank you, I'll start work on it!
