### ISSUE TITLE
Refactor Order Status Management

### ISSUE THREAD

**Issue by evgongora** [Vagabonds-Labs/cofiblocks#59]
Description:

The ProductStatusDetails component is too complex and handles multiple responsibilities. It needs to be split into smaller, focused components.

Code Reference: `ProductStatusDetails`

Acceptance Criteria:

- Split into smaller components:
- Implement proper prop typing for each component
- Add loading states for status updates
- Handle error states appropriately

**Comment by NueloSE** [comment]
Hi @evgongora can i be assigned this issue. I have experience in Typescript and Javascript and i can handle the refactor of the [`ProductStatusDetails`](#)

**Comment by martinvibes** [comment]
Hey @evgongora I would love to take on this issue Kindly assign :)

I am much interested in contributing to this repo 
Thanks

**Comment by ShantelPeters** [comment]
Hi @evgongora please can i be assigned to this issue

**Comment by mimisavage** [comment]
I'm confident I can deliver on this—may I take the lead?

**Comment by KevinLatino** [comment]
Hello @evgongora! My name is Kevin Latino, and I'm a frontend developer and active open-source contributor. I'm a member of Dojo Coding, a thriving Web3 community in Costa Rica. I have experience with React, Next.js, and TypeScript, also I have experience in data fetching and API integrations and I recently won the LATAM Hackathon hosted by Base.  I've also contributed to projects in ecosystems like Starknet and Stellar. 

I will refactor the ProductStatusDetails component by splitting it into smaller, more focused components. I’ll ensure proper prop typing for each component to improve maintainability and readability. I will also add loading states for status updates and handle error states appropriately to improve the user experience.

**Comment by derianrddev** [comment]
My Background and How It Can Be Leveraged
Hello, my name is Derian Rodríguez. I am a passionate software engineer with over one year of experience. I am part of the Dojo Coding Community and have been actively contributing to open-source projects through OnlyDust. I have experience in frontend development using JavaScript/TypeScript, React, and Next.js. I would love to contribute and support the development of this project.

How I Plan on Tackling This Issue
I will analyze the main functions of the component.
I will break those responsibilities into individual components.
I will consolidate these components within the main component so they can communicate via props and maintain centralized state.

**Comment by jimenezz22** [comment]
Hi! Can I help with this issue?. I have experience with React and Cairo, and I’ve previously refactored components in projects like ByteBeasts, ensuring cleaner structures and better maintainability.

My Approach:
Component Splitting:

Restructure ProductStatusDetails into smaller, focused components such as:
StatusBanner
ProductDetailsList
StatusUpdateModal
State Management:

Add and manage loading states for smoother status updates.
Implement error handling to provide feedback in case of issues.
Prop Typing:

Define proper prop types for each new component to improve type safety and readability.
This approach ensures better separation of concerns and makes the component easier to test and maintain

**Comment by Benjtalkshow** [comment]
I'd like to handle this task.
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

MY ETA is 48hrs. Thanks

**Comment by ShantelPeters** [comment]
Can I take this from here?

**Comment by jimenezz22** [comment]
@evgongora thanks for the issue, I will start working immediately
