### ISSUE TITLE
Integrate sign-in with Starknet and authentication with secured TRPC routes

### ISSUE THREAD

**Issue by brolag** [Vagabonds-Labs/cofiblocks#6]
Implement sign-in using Starknet for secure user authentication, and secure specific routes with TRPC.

- **Steps**:
  1. Integrate `@argent/get-starknet` for Starknet wallet authentication.
  2. Set up TRPC middleware to secure protected routes.
  3. Ensure that only authenticated users can access routes such as profile and checkout.

- **Acceptance Criteria**: Users can sign in using their Starknet wallet and securely access protected routes, while non-authenticated users are restricted.

- **Resources**: [Starknet Wallet Integration Guide](https://docs.starknet.io/docs/wallets), [TRPC Documentation](https://trpc.io/)

**Comment by devcollinss** [comment]
Hello @brolag,

I am Collins Ikechukwu, and I am eager to take on this task. With 4 years of experience as a full-stack JavaScript developer, I have a strong background in developing frontend web applications, particularly using Next.js. I’ve  contributed to OnlyDust in projects involving Next.js, Cairo, TypeScript, and JavaScript. I’m confident that I can handle this task effectively and would be grateful if you could assign it to me.
