### ISSUE TITLE
Create Contributing Guidelines (CONTRIBUTING.md) for CofiBlocks

### ISSUE THREAD

**Issue by evgongora** [Vagabonds-Labs/cofiblocks#64]
Description:

To encourage and streamline contributions to CofiBlocks, a clear and comprehensive CONTRIBUTING.md file needs to be created. This document will provide potential contributors with the necessary steps to effectively participate in the project, ensuring a consistent and collaborative development process.

Objectives:

1. Define the Contribution Process
- Include steps for checking existing issues, creating new ones, and starting work on contributions.
2. Provide Technical Guidance
- Outline how to fork and clone the repository, create branches, and follow project-specific coding conventions.
3. Clarify Pull Request Workflow
- Include detailed steps for submitting pull requests, referencing issues, and addressing maintainer feedback.
4. Encourage Collaboration
- Highlight communication channels (e.g., Telegram or other platforms) for updates and support.
	
Acceptance Criteria

1. Clear and Concise Guidelines
- The CONTRIBUTING.md file should provide easy-to-follow steps for contributors.
2. Encourage Community Engagement
- Include links to communication channels (e.g., Telegram, GitHub discussions).
3. Consistent Format
- Use headings, bullet points, and code blocks for clarity and accessibility.
4. Ready-to-Use Template
- Ensure contributors can copy and paste commands where applicable.

**Comment by GoSTEAN** [comment]
### Background 
As a technical writer looking to contribute to the CofiBlocks project, your background should emphasize your expertise in writing clear, user-friendly documentation, ensuring that all contributors and users can effectively understand and engage with the project.

**Comment by 0xdevcollins** [comment]
Can I be assigned this issue? @evgongora.

I am a Full Stack Blockchain Developer with expertise in Next.js, TypeScript, React, Node.js, and Solidity/Rust. With 46 contributions across 10 OnlyDust projects, I bring technical excellence, adaptability, and a focus on user-centric blockchain solutions.
I've written documentation for Joyboy, so I have expertise with it.

**Comment by josephchimebuka** [comment]
Can I handle this task?

**Comment by JosueBrenes** [comment]
Hi, I'm Josué Brenes and I'll be working on issue.
I'm Dojo Coding member. ⛩️

I estimate this will take 1 day to complete.

## How I Would Resolve This

To create a CONTRIBUTING.md file that effectively guides contributors, I would follow these steps:

---

### 1. **Define the Contribution Process**
   - **Checking Issues**:
     - Include instructions for contributors to first check the existing issues on the repository.
     - Suggest searching for similar issues before creating new ones.
   - **Creating New Issues**:
     - Provide a template for creating issues, encouraging contributors to include:
       - A clear description.
       - Steps to reproduce (if applicable).
       - Expected and actual results.
   - **Starting Work**:
     - Include steps to assign issues to themselves (if permitted) or communicate their intention to work on an issue through a comment.

---

### 2. **Provide Technical Guidance**
   - **Forking and Cloning**:
     - Include the following commands for contributors:
       ```bash
       # Fork the repository on GitHub
       git clone https://github.com/your-username/CofiBlocks.git
       cd CofiBlocks
       ```
   - **Branching**:
     - Define the branch naming convention (e.g., `feature/`, `fix/`, `docs/`).
       ```bash
       # Create a new branch
       git checkout -b feature/your-branch-name
       ```
   - **Coding Conventions**:
     - Add references to any project-specific guidelines (e.g., coding style, formatting rules, or linters).

---

### 3. **Clarify Pull Request Workflow**
   - Include detailed steps for submitting pull requests:
     1. Ensure code is properly tested.
     2. Commit changes with meaningful messages:
        ```bash
        git add .
        git commit -m "Fix: [Brief description of fix]"
        git push origin feature/your-branch-name
        ```
     3. Open a pull request on GitHub:
        - Provide a descriptive title.
        - Link the pull request to the relevant issue using keywords (e.g., `Closes #123`).
   - Explain how to address feedback from maintainers and update the pull request accordingly.

---

### 4. **Encourage Collaboration**
   - Include links to the project's communication channels:
     - Add links to **Telegram**, **GitHub Discussions**, or any other platform where contributors can ask questions or get updates.
   - Emphasize the importance of maintaining a respectful and collaborative environment.

---

### 5. **Acceptance Criteria**
   - **Clear and Concise Guidelines**:
     - Use plain language and avoid jargon to make the document accessible to all contributors.
   - **Encourage Engagement**:
     - Highlight the benefits of collaboration and provide resources for contributors to learn more about the project.
   - **Consistent Format**:
     - Use headings, bullet points, and code blocks for clarity.
   - **Ready-to-Use Template**:
     - Include commands and templates contributors can copy and paste.

---

### Sample CONTRIBUTING.md Content

```markdown
# Contributing to CofiBlocks

Thank you for your interest in contributing to CofiBlocks! Here are the steps to get started.

## Reporting Issues
- Before opening a new issue, check if one already exists.
- If opening a new issue, please include:
  - A clear and descriptive title.
  - Steps to reproduce the issue.
  - Expected and actual behavior.

## Forking and Cloning
1. Fork the repository on GitHub.
2. Clone your fork:
   ```bash
   git clone https://github.com/your-username/CofiBlocks.git
   cd CofiBlocks
   ```

## Working on Issues
- Create a new branch:
  ```bash
  git checkout -b feature/your-branch-name
  ```
- Follow the project's coding conventions and ensure your changes are properly tested.

## Submitting a Pull Request
1. Push your changes:
   ```bash
   git push origin feature/your-branch-name
   ```
2. Open a pull request:
   - Include a descriptive title and link it to the relevant issue (e.g., `Closes #123`).
   - Be ready to address feedback from maintainers.

## Communication
- Join our Telegram group: [Telegram Link](#)
- Participate in discussions on GitHub.

Thank you for contributing!
```

---

### 6. **Testing and Feedback**
   - Review the CONTRIBUTING.md file with team members or stakeholders.
   - Ensure it meets the objectives and aligns with project guidelines.

---

### Deliverables:
   - A complete CONTRIBUTING.md file, formatted and ready to be added to the repository.
   - Links to communication channels and templates for contributors.

---

**Comment by Kingsuite** [comment]
Can I take this from here?

**Comment by PabloVillaplana** [comment]
Hi, I'm Juan Pablo Villaplana from Dojo Coding, I'd like to contribute to this Coffee Blocks issue

To resolve this issue I would base myself on documentation from other projects and standardize it for this project, in addition to asking for feedback from Erick, Brolag or any other member of the team to verify that we are complying well with this issue.

**Comment by Joewizy** [comment]
Could I take over this issue?

**Comment by NueloSE** [comment]
May I take care of this?

**Comment by Iwueseiter** [comment]
I'm a frontend/smart contract developer and a technical writer.
Here are links to comprehensive docs I've written and have been merged Flex-NFT-Marketplace/Flex-Marketplace-Contract#107, https://github.com/cairo-book/cairo-book/pull/1019, https://github.com/horuslabsio/tokenbound-contract-docs/pull/12, https://github.com/sivicstudio/starkludo/pull/102, https://hackmd.io/@-__sK8xkRjuXHkFZQLyYXg/HkLcMImM1l.

**Comment by jsandinoDev** [comment]
Hi  I'm a full-stack developer from Costa Rica and member of Dojo coding. I've worked on projects using React, Solidity, Cairo, and blockchain tools. My skills in both front-end and back-end development allow me to build scalable and secure solutions for web3 ecosystems.

I have experience creating this guidelines files in other web3 project! I would love to work in this

**Comment by josephpdf** [comment]
Hi! @evgongora
I'm Joseph Poveda, I'm a member of the Dojo Coding community.
A bit about my background is that I'm just starting out with Only Dust and I want to contribute as much as I can to the project. My knowledge of different programming languages ​​will allow me to better solve problems.
To solve this issue I will:
1. **Define the Contribution Process:**
- Review existing issues and create new ones if necessary.
- Include clear instructions on how to start working on contributions.
2. **Provide Technical Guidance:**
- Explain how to fork and clone the repository.
- Detail how to create branches and follow the project’s specific coding conventions.
3. ** Clarify the Pull Request Workflow:**
- Include detailed steps for submitting pull requests, referencing issues, and handling maintainer feedback.
4. **Encourage Collaboration:**
- Highlight available communication channels (e.g., Telegram) for updates and support.
5. **Ensure Acceptance Criteria:**
- Create clear and concise guidelines.
- Include links to communication channels.
- Use a consistent format with headings, bullet points, and code blocks.
- Provide ready-to-use templates with commands that can be copied and pasted.
I hope this helps you structure your CONTRIBUTING.md effectively.

**Comment by aguilar1x** [comment]
May I handle this issue?

**Comment by gchimelu** [comment]
Hello CofiBlocks,
Allow me to help you create solid contributing guidelines that will help future contributors know exactly what to do when working on your project. As an experienced writer and Web3 head, I understand the need for clear-cut guidelines that would make workflow a lot more easier.

**Comment by RJMadrigal** [comment]
Hi team!

I would like to get this opportunity. I am a systems engineer from Costa Rica, with experience in C#, and I am currently learning Cairo and Rust, which makes this project a great opportunity to start my journey in OSS.

It's my first ODhack and I'm looking for my first contribution, so I'm excited to contribute and learn in this collaborative environment.

Thank you for considering me!

**Comment by Benjtalkshow** [comment]
Would love to tackle this!

**Comment by SudiptaPaul-31** [comment]
Will love to work on this issue.

**Comment by ShantelPeters** [comment]
Could I take a shot at this?

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  already make many  CONTRIBUTING.md file for many projects  .   please /assign  this issue .
Thank You

**Comment by od-hunter** [comment]
Hello can I be assigned this please? I am a blockchain developer and I'm also good at documentations.  I'll craete a clear and comprehensive CONTRIBUTING.md file that will provide potential contributors with the necessary steps to effectively participate in the project, ensuring a consistent and collaborative development process. It'll be clear and concise with consistent format.
Below are some of the documentations I've done that were merged:
https://github.com/dojoengine/book/pull/308,
https://github.com/keep-starknet-strange/joyboy/pull/143,
https://github.com/Scaffold-Stark/ss2-docs/pull/31,
https://github.com/horuslabsio/Starknet-Scaffold/pull/94,
https://github.com/Hyle-org/examples/pull/15.

Please I’m ready to work, assign me please.

**Comment by LazarusAA** [comment]
Hi! I'm Alvaro Lazarus, a developer from Dojo Coding ⛩️ with a good amount of experience writing documentation which makes me confident that I can complete this issue.

My workflow:

- Define contribution steps and workflows
- Draft clear, structured guidelines
- Add collaboration channels
- Test and finalize for usability

ETA: 24 hrs

**Comment by akintewe** [comment]
Hi, I'm akintewe and I'll be working on issue


I have experience in cairo and typescript 

I My ETA is > 24hrs to complete.

I would tackle this issue with these steps:

I am a new contributor, happy to help :)

**Comment by salazarsebas** [comment]
# My background
As a member of the Dojo Coding community, I have experience in web2 and traditional technologies, as for web3 I have only been working for a few months and I have managed to make a few contributions, however, it is not an impediment for me to do my best in this issue, I will dedicate the necessary effort to contribute to the OSS.

# How I plan on tackling this issue
To solve this issue, I will perform the following steps:

- Draft the guide for the contributors.
- Make sure the guide is clear, complete and concise. And user-friendly.
- Consult on formats they want to follow to work on it and achieve what is required.
- Ask for indications on the changes to be made.
- Make changes if necessary.

**Comment by sotoJ24** [comment]
I can take this issue, I can consider the guides to be so important for project direction, communication and more, I also know how to use the right keywords and the importance of good wording

Josué From Dojo Coding

**Comment by vestor-dev** [comment]
hey sir I'd like to handle this task.
i'm a frontend developer with experience
i would really love to contribute to your project 
kindly assign :)
