### ISSUE TITLE
Implement filter popup for the product catalog

### ISSUE THREAD

**Issue by brolag** [Vagabonds-Labs/cofiblocks#8]
Add a popup that allows users to apply filters (e.g., product type, price range) to the catalog.

- **Steps**:
  1. Create a filter component that opens as a popup.
  2. Implement filtering logic on the frontend and backend.

- **Acceptance Criteria**: Users can apply filters to the product catalog and see updated results based on selected criteria.

Blocked by: https://github.com/Vagabonds-Labs/cofiblocks/issues/7

**Comment by muguika** [comment]
User should be able to filter by  roast level, region and price to start with

![filter](https://github.com/user-attachments/assets/60c936d7-1bcf-4dc8-a696-1e1f929b348f)

**Comment by muguika** [comment]
If the search returns results... image has a little typo *found :)

![Search](https://github.com/user-attachments/assets/ca5acaa5-fbbe-4783-bb81-bfb6baadc6ea)

if the search doesn't return any results

![Search02](https://github.com/user-attachments/assets/c1333b7c-33b3-40e4-9e9c-36c0d0c8387c)

**Comment by devcollinss** [comment]
Hello @brolag,

I am Collins Ikechukwu, and I am eager to take on this task. With 4 years of experience as a full-stack JavaScript developer, I have a strong background in developing frontend web applications, particularly using Next.js. I’ve  contributed to OnlyDust in projects involving Next.js, Cairo, TypeScript, and JavaScript. I’m confident that I can handle this task effectively and would be grateful if you could assign it to me.

**Comment by AnoukRImola** [comment]
Hi! @brolag  I have experience with this type of issues, can I take it? :)

**Comment by brolag** [comment]
@AnoukRImola assigning this to you.
