### ISSUE TITLE
Deploy Smart Contracts to StarkNet Sepolia

### ISSUE THREAD

**Issue by evgongora** [Vagabonds-Labs/cofiblocks#81]
## Objective: 

Deploy the cofi_collection and marketplace contracts to the StarkNet testnet.

## Steps:

- [x] Deploy the `cofi_collection` contract using testnet-specific settings.
- [ ] Deploy the `marketplace` contract using testnet-specific settings.
- Use testnet-specific wallets and addresses.
- Verify the contract deployments using StarkNet Explorer and record the contract addresses.

**Comment by Shoetan** [comment]
Is it okay if I tackle this?

I am Emmanuel returning contributor skilled in React,Tailwind CSS, TypeScript, Cairo and Redux, with experience contributing to open-source projects on only dust
 Last cairo contributtion to Carbonable PR: https://github.com/carbonable-labs/carbon-protocol-v3/pull/82   I’ll address this issue by delivering clean, efficient, and well-documented code.  Onlydust Profile: https://app.onlydust.com/u/Shoetan

**Comment by CollinsC1O** [comment]
Could I take on this issue?

**Comment by SoarinSkySagar** [comment]
May i work on this @evgongora 
eta: 3 days

**Comment by fabrobles92** [comment]
Hello Fab here,

My experience contributing to several starknet projects including Dojo Engine where I have had experience deploying and interacting smart contracts from the code will help a lot to tackle this issue :)

**Comment by Thibrac** [comment]
I'm level 8 on node guardian, I think I can solve this issue to progress in my learning! :)

**Comment by Kingsuite** [comment]
Can I start working on this?

**Comment by Jonatan-Chaverri** [comment]
Can I take this one? Since I worked on the marketplace contract I have some experience

**Comment by Belloabraham121** [comment]
Hey! I'm Iteooluwakisi.
Member of Web3bridge. I have contributed before to other projects like:
• CoinSafe 
• Scaffold-ETH
• BuidlGuidl
Can I work on this issue?
Plan to Solve the Issue:
Study the codebase to understand the current structure and functionality.
Understand the problem that needs to be solved by thoroughly reading the issue details.
Leverage all provided resources within the issue to get a better grasp of the task at hand.
If I encounter roadblocks, I will ask questions ASAP in the relevant group/chat to move forward effectively.
I will open a PR and wait for your feedback.

**Comment by martinvibes** [comment]
i'm a frontend dev and blockchain dev 
i would love to work on this and get it done
I’m interested in this one.
kindly assign

**Comment by tasneemtoolba** [comment]
can I jump on this task? I finished the starklings and scaffold starknet challenges and would like to take this experience

**Comment by trashcancries** [comment]
May i work on this @evgongora
eta: 3 days

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by 1nonlypiece** [comment]
Hi,  
I’d like to work on this issue as I have experience with Cairo and building on StarkNet, including writing and optimizing smart contracts.  

ETA:  
I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by ShantelPeters** [comment]
I'd like to handle this task.

**Comment by vestor-dev** [comment]
hey sir i would love to work on this issue 
i'm a blockchain dev and i would love to handle this issue 
assign me and i'll get to work

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by mimisavage** [comment]
I’d like to work on this.

**Comment by OWK50GA** [comment]
May I take care of this?

**Comment by od-hunter** [comment]
Hi, please can I be assigned this please? I would love to be the given the opportunity to solve this issue please. I have experience in html, css, JavaScript, TypeScript, cairo and rust.

1. I'll configure StarkNet-specific tools (starknet-devnet, cairo-lang) and ensure testnet wallets (e.g., ArgentX) are funded with testnet ETH.
2. I'll compile cofi_collection.cairo and marketplace.cairo to generate StarkNet-compatible bytecode (cofi_collection_compiled.json, marketplace_compiled.json)
3. I'll set testnet parameters in the deployment script (e.g., network=testnet, wallet private keys).
4. I'll deploy cofi_collection and marketplace using the CLI and Capture transaction_hash and contract_address for each deployment.
5. If dependencies exist (e.g., marketplace depends on cofi_collection), I'll invoke initialization functions, I'll also verify deployments on StarkNet Explorer using contract_address or transaction_hash.
6. Lastly I'll test. 

I'll create a pr within 2 days upon assignment.
Kindly assign me please, I'm up for the task.

**Comment by TheSQLguy** [comment]
To deploy the cofi_collection and marketplace contracts to the StarkNet testnet, I will:

Deploy the cofi_collection contract:
Configure the contract with testnet-specific settings, such as network settings, wallets, and addresses.
Deploy the contract using the correct wallet connected to the StarkNet testnet.
Deploy the marketplace contract:

Similarly, deploy the marketplace contract using testnet-specific settings.
Verify Deployments:

After successful deployments, I will verify them on the StarkNet Explorer to ensure that both contracts are correctly deployed.
Record the contract addresses for easy integration into the front-end.

**Comment by Baronvil** [comment]
Could I grab this task?

**Comment by suhas-sensei** [comment]
Could I grab this task? I'll deploy the cofi_collection and marketplace contracts to StarkNet testnet using Starknet.js, handling deployment parameters for the testnet environment. Having experience with StarkNet contract deployments and marketplace implementations, I'll ensure proper verification and record the contract addresses on completion.

**Comment by caxtonacollins** [comment]
Can I take this from here?

**Comment by DuendexCR** [comment]
Can I take this issue?

**Comment by savagechucks** [comment]
Yo, I'm Isaac, a frontend developer...
I just recently joined onlydust so I'm a new contributor.
I'd appreciate it if I can be assigned to this issue.

**Comment by 0xprivateChaos** [comment]
Hey can I pick this issue?

**Comment by Emmanex01** [comment]
I'm Emmanuel Tochukwu, 
A Frontend developer, proficient in Reactjs, tailwindcss, typescript, Cairo Programming Languages.
I'd like to handle this task?

**Comment by mananuf** [comment]
Could I be assigned to this?

**Comment by Favvie** [comment]
I'd love to work on this!

**Comment by Favvie** [comment]
Request to Deploy StarkNet Contracts on Testnet

Hello Team,
I would like to take on the task of deploying the cofi_collection and marketplace contracts on the StarkNet testnet. I'll ensure the following steps are carried out precisely:

Plan of Action:

Contract Deployment Preparation:
- Set up testnet environment
- Set up testnet wallets with sufficient test tokens for deployment

Deployment Process:
- Deploy cofi_collection contract using Cairo compiler and StarkNet CLI
- Deploy marketplace contract following similar testnet deployment procedures
- Use configured testnet parameters and wallet addresses

Verification and Documentation:
- Use StarkNet Explorer to verify successful contract deployments
- Capture and record the precise contract addresses

ETA:
24 Hours

I will ensure the final implementation meets all the requirements and follows the Contributor’s Guide. Let me know if there are additional details or expectations for this task.

Thank you!
Favour Abangwu

**Comment by Dorcas18** [comment]
I'd like to handle this task.

**Comment by ekumamatthew** [comment]
Could I try solving this?

**Comment by od-hunter** [comment]
@evgongora , thank you ser, will get to it🙏🏻

**Comment by fabrobles92** [comment]
@od-hunter Any update regarding this one? This is blocking my issue.

**Comment by od-hunter** [comment]
> @od-hunter Any update regarding this one? This is blocking my issue, this has 4 days since it was assigned.

Ser @fabrobles92 , I messaged @evgongora concerbing my issue already but he’s yet to reply

**Comment by evgongora** [comment]
GM! Still having issues with this?

**Comment by bitfalt** [comment]
hii! i'd love to have this issue for the Marketplace deployment.
