### ISSUE TITLE
Validate Ownership of Minted NFTs

### ISSUE THREAD

**Issue by evgongora** [Vagabonds-Labs/cofiblocks#85]
## Objective:

Ensure producers can only list NFTs they own.

## Steps:

Use the balanceOf method in the cofi_collection contract to verify the producer's ownership of the NFT.
Implement a validation check in the back-end or front-end before allowing the listing process to proceed.

**Comment by robertram** [comment]
Hi, I am from the Dojo Coding community and a new contributor to Only Dust. I'm a Web3 frontend developer and founder of an NFT ticketing platform.

The way I would approach this feature is as follows:

Utilize the balanceOf Method:
On the front-end, I would integrate a call to the balanceOf method of the cofi_collection contract. This call will check whether the producer owns the specified NFT by comparing their address to the token owner's address.

Implement Validation Logic:
On the front-end, I would add a validation step before initiating the listing process. If the producer does not own the NFT, the "List" button would be disabled, or an error message would be displayed.
On the back-end, I would implement a secondary validation step to recheck ownership using the same balanceOf method to ensure the integrity of the system.

**Comment by tasneemtoolba** [comment]
can I take this issue? I'm a full-stack who tries to gain more experience in web3 space!

**Comment by KevinMB0220** [comment]
Hi, I'm Kevin, I have experience working with Cairo as I'm developing a game with this language and I make contributions to Cairo in open source.

**Comment by aradix16** [comment]
Hi! I've already contributed to Cairo projects during the prev ODHack10 and would love to work on this issue.  I already worken on an ERC721 contract, so this task would be a good next step. Thanks :)

**Comment by Jonatan-Chaverri** [comment]
Hi! Can I take this one? This should definitely be done in the backend for security purposes.

**Comment by ryzen-xp** [comment]
Hi, I am a proficient blockchain developer, expert in Cairo, Rust, Solidity, Aptos, and web development. I have contributed to projects like Chainevents and Arkprojects sunshine lab etc .

I can implement the validation check using the balanceOf method in the cofi_collection contract to ensure producers can only list NFTs they own. Please assign this issue to me.
Thank you!

**Comment by anihdev** [comment]
Hi Could I take over this issue? Im a backend developer experienced in writing cairo and solidity, you can check my github repo, to handle this;


ill use balanceOf to check NFT ownership
Return true if the producer owns at least one NFT
Provides a method to set the collection contract address
ill also make sure evrything is folows the requrimwnts of balanceof

still open for redirection from maintainers

**Comment by Jagadeeshftw** [comment]
Hi,
I’d love to work on this issue as I have strong experience with front-end development. Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by 1nonlypiece** [comment]
Hi ,
I’d like to work on this issue as I have experience in building frontend interfaces using frameworks like React and Next.js.


ETA:
 I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by ShantelPeters** [comment]
Could I grab this task?

**Comment by mimisavage** [comment]
May I take this issue on?

**Comment by No-bodyq** [comment]
May I be assigned to this?

**Comment by TheSQLguy** [comment]
I am new to open source and love to contribute.
To ensure that only the producers can list NFTs they own, I will make use of the balanceOf method in the cofi_collection contract to verify whether the producer owns the NFT. This check is done in either the back-end or front-end so that only producers who own the NFT are allowed to proceed with listing. If the producer does not own the NFT, listing is blocked.

**Comment by Baronvil** [comment]
I would love to take on this issue.

**Comment by suhas-sensei** [comment]
I’d love to work on this task. Having worked with NFT marketplaces, I'll ensure secure ownership verification in both backend and frontend listing flows while preventing unauthorized listings.
I'll implement ownership validation checks for NFT listings, using the cofi_collection contract's balanceOf method before allowing producers to list tokens.

**Comment by caxtonacollins** [comment]
May I take care of this?

**Comment by DuendexCR** [comment]
Is it okay if I tackle this?

**Comment by tosinmoses384** [comment]
Can I contribute to this one?

**Comment by Amarjeet325** [comment]
Can I jump on this task?

**Comment by olisaagbafor** [comment]
Could I try solving this?

**Comment by 3th-Enjay** [comment]
I’m interested in this one.

**Comment by ekumamatthew** [comment]
Could I take on this issue?

**Comment by Jonatan-Chaverri** [comment]
I tried to tackle this one however I was told by @evgongora that this is no longer needed since it does not follow the UX flow.
