### ISSUE TITLE
Integrate Marketplace Listing Functionality

### ISSUE THREAD

**Issue by evgongora** [Vagabonds-Labs/cofiblocks#86]
## Objective:

Allow producers to list their NFTs on the marketplace.

## Steps:

Integrate the marketplace contract's create_product method into the back-end or front-end.
Capture and validate listing details such as price and stock from the form.
Pass the listing details to the marketplace contract during the transaction.

**Comment by tasneemtoolba** [comment]
can I take this issue? I do have experience in the project's stack(both cairo and typescript), but I'm trying to gain more!

**Comment by JoE11-y** [comment]
I'd love to work on this!

**Comment by abdegenius** [comment]
May I be assigned to this?

**Comment by josephchimebuka** [comment]
May I pick this up?

**Comment by zintarh** [comment]
I'd love to work on this!

**Comment by jimenezz22** [comment]
Hi, I'd love to contribute to this issue! I'm part of the Dojo Coding community and have experience contributing to various open-source projects in OnlyDust and I manage a full-stack developer profile. 

My Approach:
Integration with the Marketplace Contract

Identify and integrate the create_product method from the marketplace contract.
Ensure seamless interaction with the contract, leveraging appropriate libraries or SDKs (e.g., Starknet.js) for transactions.
Form Handling

Capture listing details (price, stock, etc.) through a user-friendly form on the front-end.
Validate the inputs to prevent incorrect or malicious data before passing them to the contract.
Transaction Management

Pass the validated listing details (price, stock) to the create_product method during the transaction.
Implement error handling to manage transaction failures, providing meaningful feedback to the user.
Testing and Validation

Write unit tests for the integration logic to ensure proper interaction with the contract.
Test the front-end form validation and back-end transaction handling for edge cases.

**Comment by ONEONUORA** [comment]
Is it okay if I take this? I am a full stack and blockchain developer. ETA 24 hours

**Comment by 0xdevcollins** [comment]
Can I be assigned this issue?

My Background
I am a Full Stack Blockchain Developer with proficiency in Solidity/Rust, Next.js, TypeScript, React, and Node.js. I've demonstrated my ability to adjust to a variety of requirements, perform well under pressure, and reliably produce user-centric blockchain solutions with 58 significant contributions spread over 17 OnlyDust projects.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by Jagadeeshftw** [comment]
Hi,
I’d love to work on this issue as I have strong experience with front-end development. Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by akintewe** [comment]
Hello, I am a Full Stack Developer with a strong background in  Next.js/React, TypeScript, and Rust.  I would like to work on this issue 
Would love to newly contribute :) 
ETA is 12 hours .

**Comment by ShantelPeters** [comment]
I'd love to give this a go.

**Comment by Supa-mega** [comment]
Is it okay if I take this?

**Comment by ryzen-xp** [comment]
Hi, I am a proficient blockchain developer, expert in Cairo, Rust, Solidity, Aptos, and web development. I have contributed to various projects like Chainevents and Arkprojects.

I will integrate the create_product method from the marketplace contract, ensuring listing details like price and stock are captured and validated, then passed to the contract for the transaction.

Please assign this issue to me.

Thank you!

**Comment by Amarjeet325** [comment]
May I pick this up?

**Comment by Michaelkingsdev** [comment]
Is this issue still available?

**Comment by mimisavage** [comment]
Can I take this issue?

**Comment by emarc99** [comment]
Can I start working on this?

**Comment by OWK50GA** [comment]
Could I try solving this?
Hi, I'm Wilfrid Okorie, a Frontend Web Developer and Cairo Dev, and I'd like to take this issue.
I have experience building Frontends for Web 3 and integrating with their contracts. 

My approach:
I will go through the project to see the structure and the dependencies, so that I will know what kind of tools are available to me in the codebase. 
I will then go to the component that renders the form, and look for the submit function of the form. 
I will look through the contract to see what I require for the integration of the said method into the Frontend. 
In the function, I will use a mix of React hooks and starknetjs or Starknet-React hooks to ensure the contract call is done, depending on the state-of-the-art I saw when I went through the project. 

Expect my first PR within 48 hours of being assigned

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by Luluameh** [comment]
Can I take this from here?

**Comment by Yunusabdul38** [comment]
Can I contribute to this one?

**Comment by caxtonacollins** [comment]
Can I attempt this issue?

**Comment by DuendexCR** [comment]
I'd love to give this a go.

**Comment by davedumto** [comment]
Hello, I'm David, a new open-source contributor, proficient in TypeScript, JavaScript, Tailwind CSS, and ShadCN. I can help integrate the marketplace contract's create_product method by:
Capturing and validating listing details (price, stock) from the form.
Integrating the method into the back-end or front-end to submit listing details to the marketplace contract.
ETA: 2 days

**Comment by Emmanex01** [comment]
I'd love to work on this!

**Comment by 3th-Enjay** [comment]
Can I try solving this issue i think i can ?

**Comment by Dorcas18** [comment]
Mind if I try this one?

**Comment by ekumamatthew** [comment]
Can I try solving this issue?

**Comment by Jayrodri088** [comment]
Hi, I’m John Asogwa, and I’d like to work on this issue.

I have over three years of experience with React, TypeScript, and blockchain integrations, making me well-suited for implementing this feature. I’m excited to contribute to Cofiblocks’ mission of empowering coffee farmers and building a sustainable marketplace.

Steps to Resolve
Integrate the create_product Method

Review the marketplace contract’s documentation to understand the required parameters.
Integrate the create_product method into the frontend or backend, depending on the project architecture.
Extend the Register-Coffee Form

Add fields for price and stock with proper validation:
Price must be a positive number.
Stock must be a positive integer.
Validate and Capture Data

Use frontend validation libraries to ensure accurate inputs.
Add a backend layer for further validation to ensure data integrity.
Test and Simulate Transactions

Use a testnet or local blockchain environment to simulate calls to the create_product method.
Test edge cases like invalid inputs and confirm error handling works properly.
Enhance UX

Add notifications for successful and failed transactions to keep producers informed.
Provide feedback during loading states (e.g., using a spinner).
Timeline
Day 1: Extend the form, integrate the create_product method, and handle data validation.
Day 2: Test the implementation, refine UX feedback, and finalize the PR.
I’m confident I can complete this task in 2 days and deliver a seamless NFT listing functionality for the marketplace. Looking forward to contributing to Cofiblocks!
