### ISSUE TITLE
Implement search feature for the product catalog

### ISSUE THREAD

**Issue by brolag** [Vagabonds-Labs/cofiblocks#9]
Add a search bar to allow users to search for products in the catalog.

- **Steps**:
  1. Implement a search bar in the catalog page.
  2. It should show related products.

- **Acceptance Criteria**: Users can search for products, and search results are displayed dynamically.

Blocked by: https://github.com/Vagabonds-Labs/cofiblocks/issues/7

**Comment by muguika** [comment]
Search in the catalog home

![Search01](https://github.com/user-attachments/assets/6005f338-e24c-4fa4-9816-4bf2ba62f979)

Search results (little typo, it's "found")

![SearchResults](https://github.com/user-attachments/assets/5dd70f40-dd7b-4a54-b3ee-6bc721329a04)

Search no results

![SearchNoResults](https://github.com/user-attachments/assets/ad55746d-762d-4dd5-8ac6-3d4daa3bf199)

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/cofiblocks).

### My background and how it can be leveraged
Hello @brolag,

Can I work on this task? I am ready and available to take it on. I’m an experienced full-stack JavaScript developer with 4 years of experience and a passion for developing frontend web applications. I specialize in using Next.js to build full-stack applications. I have made over 18 contributions on OnlyDust in Next.js, Cairo, TypeScript, and JavaScript projects. I would be glad if this task is assigned to me.

**Comment by devcollinss** [comment]
Hello @brolag,

I am Collins Ikechukwu, and I am eager to take on this task. With 4 years of experience as a full-stack JavaScript developer, I have a strong background in developing frontend web applications, particularly using Next.js. I’ve  contributed to OnlyDust in projects involving Next.js, Cairo, TypeScript, and JavaScript. I’m confident that I can handle this task effectively and would be grateful if you could assign it to me.

**Comment by diegoTech14** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/cofiblocks).

### My background and how it can be leveraged
Hello @brolag I'm a software engineer from Costa Rica and I have experience working with  Typescript, Prisma and JS in general, I would love to help with this issue.

### How I plan on tackling this issue
`1.` I will begin by thoroughly reviewing the project to gain a comprehensive understanding of its context. 
`2.` I will proceed to develop the functionality for searching products within a specific catalog. 
`3.` I will display the related products accordingly.

Let me know if there's anything else you'd like me to keep in mind!

Kind regards,

Diego Duarte Fernández

**Comment by brolag** [comment]
Hi @diegoTech14, assining this to you.

**Comment by diegoTech14** [comment]
Thank you sir, I'll start ASAP!

**Comment by brolag** [comment]
@diegoTech14 in order to sync work with https://github.com/Vagabonds-Labs/cofiblocks/issues/8 let's consider creating a client state using jotai-trpc

https://jotai.org/docs/extensions/trpc
https://codesandbox.io/p/devbox/github/jotai-labs/jotai-trpc/tree/main/examples/01_typescript?file=%2Fsrc%2Fmain.tsx 

The idea is to have a atom with the listed products and enable a way to filter them setting a value after filtering. This way we can have the filter outsite the products feature if required.

https://jotai.org/docs/core/use-atom

Let me know your thoughts on this.

**Comment by qgatssdev** [comment]
hey @brolag, is this issue resolved? I have experience managing state with Jotai and would be able to finish the feature.
